beforeEach( () => {
  cy.viewport(1600, 1000)
  cy.visit('https://www.hsbc.co.in/')  
})

Cypress.on('uncaught:exception', (err,runnable) => {
  return false;
})

describe('Credit card flow test', () => {
  it('Credit card test scenarios', () => {
    cy.screenshot()
    cy.wait(3000)
    //trigger('mouseover') -----//li[1]//span[text()='Banking'] ----//span[text()="Banking"] invoke('show')
    cy.xpath('//li[1]//span[text()="Banking"]').eq(0).invoke('show').click()
    cy.screenshot()
    cy.wait(3000)
    // this are things tried for nxt point
    // cy.get('div.links-group>a[tabindex="-1"]').contains('h2','Credit Cards').click()
    //cy.get('div.links-group>a[tabindex="-1"]').eq(0).click({force: true})
    cy.xpath('//h2[text()="Credit Cards"]').eq(0).click({force: true})
    cy.screenshot()
    cy.wait(3000)
    // cy.xpath('//h1[text()="Credit cards"]').should('be.visible')
    cy.contains('h1','Credit cards').should('be.visible')  
    cy.screenshot()
    cy.wait(3000)
    cy.xpath('//span[text()="HSBC Cashback Credit Card"]').should('be.visible')
    cy.screenshot()
    cy.wait(3000)
    cy.xpath('//span[text()="HSBC Cashback Credit Card"]').click()   
    cy.screenshot()
    cy.wait(3000) 
    cy.xpath('//span[text()="Apply now"]').eq(0).should('be.visible')
    cy.xpath('//span[text()="Apply now"]').eq(1).should('be.visible')
    cy.screenshot()
    cy.wait(3000)
    cy.url().should('include','credit-cards/products/visa-cashback/')
    cy.screenshot()
    cy.wait(3000)
    cy.get('img#pp_intro_image_3').should('be.visible')
    cy.screenshot()
    cy.wait(3000)
    cy.xpath('//span[contains(text(),"INR999")]').eq(0).should('be.visible')
    cy.screenshot()
    cy.wait(3000)
    cy.xpath('//span[contains(text(),"INR200,000")]').eq(0).should('be.visible')
    cy.screenshot()
    cy.wait(3000)
    cy.get('img[alt="Chat"]').should('be.visible')
    cy.screenshot()
    cy.wait(3000)
    cy.get('img[alt="HSBC India Bank"]').eq(0).click()
    cy.screenshot()
    cy.wait(3000)
    cy.title().should('eq','HSBC India - Credit Cards, NRI Services, Saving and Deposit')
    cy.screenshot()
    cy.wait(3000)
  })
})